/**
 * Tool: create_patch_pr
 *
 * The only tool that mutates the outside world. It branches off the repo's
 * default branch, commits the patched file(s), and opens a pull request that
 * Qodo (per the hackathon workflow) reviews via `/agentic_review`.
 *
 * This tool is registered in the agent spec under `require_approval_for_tools`,
 * so TrueForge will NOT run it until a human approves the pending decision.
 */
import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { GitHubService } from '../../services/github.js';
import { guard } from '../guard.js';
import { createPatchPrShape } from '../schemas.js';

export function registerCreatePatchPr(server: McpServer, gh: GitHubService, defaultRepo: string): void {
  server.registerTool(
    'create_patch_pr',
    {
      title: 'Open remediation pull request',
      description:
        'Branch off the default branch, commit the patched file(s), and open a pull request ' +
        'with the security fix. Only call this AFTER human approval has been granted.',
      inputSchema: createPatchPrShape,
    },
    guard('create_patch_pr', async ({ repo, title, summary, files }) => {
      const target = repo ?? defaultRepo;
      const branch = `tartarus/fix-${Date.now().toString(36)}`;

      const body =
        `${summary}\n\n---\n` +
        '🛡️ _Generated by **Tartarus**, an autonomous SecOps agent on TrueForge._\n' +
        'Exploit was confirmed in an isolated sandbox and this patch was approved by a human ' +
        'before opening. Please run `/agentic_review` (Qodo) on this PR.';

      const pr = await gh.openPatchPr({ repo: target, branch, title, body, files });
      return {
        content: [{
          type: 'text',
          text: JSON.stringify({ status: 'pr_opened', number: pr.number, url: pr.url, branch }, null, 2),
        }],
      };
    }),
  );
}
